# Generated by Django 5.0.6 on 2024-09-06 17:38

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='date of event')),
                ('description', models.CharField(max_length=200)),
                ('locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\- ]*$', 'Only alphanumeric characters, hyphens and spaces are allowed.')])),
                ('description', models.CharField(max_length=200)),
                ('tag_line', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logos')),
                ('banner', models.ImageField(upload_to='banners')),
                ('path', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser_name', models.CharField(max_length=50, verbose_name='Name')),
                ('purchaser_whatsapp', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='WhatsApp')),
                ('purchaser_revolut', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='Revolut username')),
                ('pizza_type', models.CharField(max_length=100)),
                ('price_per_slice', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Price per slice')),
                ('available_slices', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSlices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=50, verbose_name='Name')),
                ('buyer_whatsapp', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='WhatsApp')),
                ('number_of_slices', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
            ],
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_organisation_name', violation_error_message='Organisation name already exists.'),
        ),
        migrations.AddField(
            model_name='event',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.organisation'),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='pizzaslices',
            name='pizza_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.pizzaorder'),
        ),
    ]
