# Generated by Django 5.0.8 on 2024-09-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='tag_line',
        ),
    ]
