# Generated by Django 5.0.2 on 2024-04-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_pizzaorder_pizzaslices_delete_passenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizzaslices',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.pizzaorder'),
            preserve_default=False,
        ),
    ]
