# Generated by Django 5.1.6 on 2025-02-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_organisation_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='stripe_account_verified',
            field=models.BooleanField(default=False),
        ),
    ]
