# Generated by Django 5.1.6 on 2025-02-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_organisation_stripe_account_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='stripe_account_id',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
