# Generated by Django 5.1.6 on 2025-04-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_squashed_0004_alter_organisation_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serving',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serving',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='serving',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchaser_name',
            field=models.CharField(max_length=50, verbose_name='Your Name'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
