# Generated by Django 5.0.2 on 2024-04-04 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_event_pizzaslices_pizza_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='available_slices',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
