# Generated by Django 5.1.6 on 2025-04-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_serving_is_locked_serving_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serving',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='serving',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='serving',
            name='stripe_checkout_session_id',
        ),
    ]
