# Generated by Django 4.2.11 on 2024-04-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_pizzaorder_available_slices'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='price_per_slice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
