# Generated by Django 5.0.6 on 2024-08-13 13:26

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_host_event_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\- ]*$', 'Only alphanumeric characters, hyphens and spaces are allowed.')])),
                ('description', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='logos')),
                ('banner_image', models.ImageField(upload_to='banners')),
                ('path', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='org_name_unique'),
        ),
        migrations.AddField(
            model_name='event',
            name='organisation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.organisation'),
            preserve_default=False,
        ),
    ]
