# Generated by Django 5.0.6 on 2024-08-13 13:42

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_organisation_organisation_org_name_unique_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organisation',
            name='org_name_unique',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='path',
            field=models.SlugField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_organisation_name', violation_error_message='Organisation name already exists.'),
        ),
    ]
