# Generated by Django 5.0.6 on 2024-08-15 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_organisation_org_name_unique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='banner_image',
            new_name='banner',
        ),
        migrations.AddField(
            model_name='organisation',
            name='tag_line',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='web_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\- ]*$', 'Only alphanumeric characters, hyphens and spaces are allowed.')]),
        ),
    ]
