# Generated by Django 5.0.6 on 2024-08-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_rename_banner_image_organisation_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='web_link',
        ),
    ]
