services:
  django-web:
    build: .
    container_name: pizzapool-docker
    #    network_mode: "host"
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      LOGLEVEL: ${LOGLEVEL}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USERNAME: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
    env_file:
      - .env
